version: '3.7'
services:
  database:
    image: postgres
    container_name: database_socialdogs
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=socialdogs
      - POSTGRES_DB=socialdogs
    volumes:
      - pgdata:/data/postgres
  
  app:
    build: .
    container_name: socialdogs
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local